spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: chaos-monkey


logging:
  level:
    com.mac.doc: DEBUG

jwt:
  header: Authorization
  secret: Y2xlbWFkbzEtbWFjLWRvYy1zZWNyZXQta2V5LWp3dC10b2tlbi0xMjM0NTY3ODkwLWhlbGxvLXdvcmxkLXNlY3JldC1rZXkK
  token-validity-in-seconds: 86400

server:
  servlet:
    session:
      tracking-modes: cookie
management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey
