spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.mac.doc: DEBUG

jwt:
  header: Authrization
  secret: Y2xlbWFkbzEtbWFjLWRvYy1zZWNyZXQta2V5LWp3dC10b2tlbi0xMjM0NTY3ODkwLWhlbGxvLXdvcmxkLXNlY3JldC1rZXkK
  token-validity-in-seconds: 86400

server:
  servlet:
    session:
      tracking-modes: cookie

