spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: chaos-monkey


logging:
  level:
    com.mac.doc: DEBUG

jwt:
  header: Authorization
  secret: Y2xlbWFkbzEtbWFjLWRvYy1zZWNyZXQta2V5LWp3dC10b2tlbi0xMjM0NTY3ODkwLWhlbGxvLXdvcmxkLXNlY3JldC1rZXkK
  token-validity-in-seconds: 86400

server:
  servlet:
    session:
      tracking-modes: cookie
management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey

# chaos monkey 활성화 http post localhost:8080/actuator/chaosmonkey/enable
# chaos monkey 활성화 확인 http localhost:8080/actuator/chaosmonkey/status
# chaos monkey watcher 확인 http localhost:8080/actuator/chaosmonkey/watchers
# chaos monkey 지연 공격 설정 http post localhost:8080/actuator/chaosmonkey/assaults level=3 latencyRangeStart=2000 latencyRangeEnd=5000 latencyActive=true
chaos:
  monkey:
    watcher:
      repository: true
    enabled: true

# 에러 발생 재현 방법
# http POST localhost:8080/actuator/chaosmonkey/assaults level=3 latencyActive=false exceptionsActive=true exception.type=java.lang.RuntimeException

